name: Build Android

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Init Flutter Project
        run: |
          flutter create --platforms=android .
          git checkout lib/main.dart pubspec.yaml || true
        working-directory: ./client

      - name: Install dependencies
        run: flutter pub get
        working-directory: ./client

      - name: Build APK
        run: flutter build apk --release
        working-directory: ./client

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: client/build/app/outputs/flutter-apk/app-release.apk